### ISSUE TITLE
anvi-refine can't save refined bins

### ISSUE THREAD

**Issue by rikander** [meren/anvio#187]
Tried to refine a bin and save it to the database. Got the following error. This is the latest version of anvi'o (just did a git pull to double-check). It's possible I'm just doing something wrong...

[12 Aug 15 18:44:05 Storing refined bins] accessing to collection "FS877_bins" ...                                                                                                                                                          Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/bottle-0.12.8-py2.7.egg/EGG-INFO/scripts/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/site-packages/bottle-0.12.8-py2.7.egg/EGG-INFO/scripts/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/site-packages/anvio-1.0.1-py2.7-macosx-10.10-x86_64.egg/EGG-INFO/scripts/anvi-refine", line 254, in store_refined_bins
    r.store_refined_bins(data, colors)
  File "/usr/local/lib/python2.7/site-packages/anvio-1.0.1-py2.7-macosx-10.10-x86_64.egg/anvio/refine.py", line 106, in store_refined_bins
    collection_dict = self.collections.get_collection_dict(self.collection_id)
AttributeError: 'RefineBins' object has no attribute 'collections'

**Comment by meren** [comment]
Thank you very much for this report, Rika.

**Comment by meren** [comment]
@rikander, it is fixed now, but I will have to make a new release for it to appear in the stable version.

Alternatively you can get rid of your current installation, and re-install the codebase from the Github current.

I am sorry this took a bit of time to fix.

Thanks again.
