### ISSUE TITLE
user / login variables

### ISSUE THREAD

**Issue by meren** [meren/anvio#253]
Hi Tobi,

I run into some bugs in the usermanagement class. I fixed one of them (cf6fe792da30960b8294484c9a1cf3a9e8c0805d), but it seems there are more, so I wanted to file an issue: 

``` python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/meren/Desktop/MBL/anvio/bin/anvi-server", line 169, in share_project
    return multiroutes.share_project(request, userdb, response)
  File "/Users/meren/Desktop/MBL/anvio/anvio/bottleroutes_multi.py", line 124, in share_project
    return json.dumps(share = userdb.create_view(get_user(request, userdb, response), request.forms.get('name'), request.forms.get('project'), request.forms.get('public')))
  File "/Users/meren/Desktop/MBL/anvio/anvio/usermgmt.py", line 670, in create_view
    p = (pname, login)
NameError: global name 'login' is not defined
```

You can reproduce this one by running `./run_server_test.sh mock`, and then logging in (username: tobi / passord: test), and try to publicly share one of the projects.

I am curious whether we can come up with a way to test all scenarios to catch these kinds of bugs early on :)

Thanks,

**Comment by paczian** [comment]
fixed with #259
