### ISSUE TITLE
anvi-self-test fails

### ISSUE THREAD

**Issue by amineche** [meren/anvio#384]
I've installed anvio  (version 2.0.2) and all required dependencies. But when I run the anvi-self-test command, I get the following error at the step : "Importing a state file into the merged profile" :

Traceback (most recent call last):
  File "/usr/local/bin/anvi-import-state", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.0.2', 'anvi-import-state')
  File "/usr/local/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/usr/local/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/usr/local/lib/python2.7/site-packages/anvio-2.0.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/anvi-import-state", line 59, in <module>
    main(args)
  File "/usr/local/lib/python2.7/site-packages/anvio-2.0.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/anvi-import-state", line 31, in main
    filesnpaths.is_file_json_formatted(args.state)
  File "/usr/local/lib/python2.7/site-packages/anvio-2.0.2-py2.7-linux-x86_64.egg/anvio/filesnpaths.py", line 204, in is_file_json_formatted
    json.load(open(file_path, 'rU'))
IOError: [Errno 2] No such file or directory: 'example_state.json'

**Comment by meren** [comment]
Hi Mohamed,

I apologize for that. That is totally my fault, and is now fixed in commit fb8d8b0d697ae072b60231f0623290c09e2176df.

If you update your repo and reinstall anvi'o, things should run.


Best,

**Comment by amineche** [comment]
Thank you. It works now :)

Best

2016-07-28 5:27 GMT+02:00 A. Murat Eren <notifications@github.com>:
