### ISSUE TITLE
anvi-pan-genome KeyError: 'percent_complete'  

### ISSUE THREAD

**Issue by metacrobe** [meren/anvio#405]
Just an FYI--running anvi-pan-genome command on some low completion SAGs. Kept getting this error and traced it to an especially incomplete genome. When this genome is removed command proceeds as normal. I looked and the genome appears to only have 2 single copy genes and only 155 total genes--should be removed anyway :). Perhaps I missed some flag for the command but here is the Traceback. Log file also attached

[log.txt](https://github.com/meren/anvio/files/516297/log.txt)

```
Traceback (most recent call last):
  File "/usr/local/bin/anvi-pan-genome", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.0.3', 'anvi-pan-genome')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/anvio-2.0.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/anvi-pan-genome", line 99, in <module>
    pan.process()
  File "/usr/local/lib/python2.7/dist-packages/anvio-2.0.3-py2.7-linux-x86_64.egg/anvio/panops.py", line 677, in process
    samples_info_file_path = self.gen_samples_info_file()
  File "/usr/local/lib/python2.7/dist-packages/anvio-2.0.3-py2.7-linux-x86_64.egg/anvio/panops.py", line 571, in gen_samples_info_file
    new_dict[header] = c[header]
KeyError: 'percent_complete'
```

**Comment by meren** [comment]
Good catch! Thanks for this. I am curious whether this is an issue in the new workflow I've been cooking in another branch. I'll look into this.

Best,

**Comment by meren** [comment]
This should be fixed in the master :)

Next release will be much better for working with pangenomes!

Thank you,
